---
title: "Take-home Exercise 2: Urban Applications of Raster-based GIS Analysis"
date: "`r Sys.Date()`"
format: html
---

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 2. Students must review and understand them before getting started with the take-home exercise.

### The Task

Elevation and related terrain variables are important in most people lives. Terrain determines the natural availability and location of surface water, and hence soil moisture and drainage. Terrain also strongly influences the location and nature of transportation networks, and the cost and methods of house and road construction. Prior to the introduction of GIS, the modelling and analysis of terrain data was a very mathematically demanding process which was usually only performed by geoscience and mapping science specialists. Today, modern GIS tool such as QGIS has made terrain modelling, anaysis and mapping relatively easy to perform by casual data analysts.

In this take-home exercise, you are required to apply appropriate analysis tools of QGIS to perform the following tasks and analysis:

-   To assemble, extract and building the following GIS layers:

    -   Bukit Timah Natural Reserve boundary

    -   DEM for the study area.

    -   Cycling paths and walking paths

    -   View points

-   Perform and prepare a visibility analysis report by using the view points layer. The report should include maps and a short write-up of not more than 300 words discussing the findings of the analysis and recommendation.

-   Perform and profile analysis report by using the the [cycling paths](https://www.nparks.gov.sg/-/media/nparks-real-content/gardens-parks-and-nature/parks-and-nature-reserve/bukit-timah-nature-reserve/btnr-maps/bt-mbt_aug-2018.ashx?la=en&hash=CEB9254091D2C4D557371AE0C581D81E2E04EEB6) and [walking paths](https://www.nparks.gov.sg/-/media/nparks-real-content/gardens-parks-and-nature/parks-and-nature-reserve/bukit-timah-nature-reserve/btnr-maps/btnr-base-map_170921_pathed.ashx?la=en&hash=F60BA3509131B55C1C5EF286EDDFF27598C6C4F3). The report should include maps and a short write-up of not more than 600 words discussing the findings of the analysis and recommendation.

### The Data

For the purpose of this study, Bukit Timah Natural Reserve planning subzone will be used. The following data and data source are highly recommended:

-   URA Master Plan 2019 Subzone Boundary. This data set can be download from data.gov.sg

-   STRM 30m Digital Elevation Model (DEM) [USGS Earth Explorer](https://earthexplorer.usgs.gov/) portal.

-   Appropriate GIS data from OpenStreetMap (OSM)

## Take-home Exercise Deliverable

### GIS data repository

The GIS repository includes but not limited to geospatial data compiled and derived, QGIS project file and data dictionary. It must be in a single zipped file (i.e. .zip). The geospatial data must be stored in a GeoPackage database format. The data dictionary can be in either MS Word document or edited into the GIS data.The project deliverable must be uploaded onto eLearn.

### Take-home Exercise Report

You are required to edit your take-home exercise report in MS Word format. The take-home exercise report, beside others, should include all the thematic maps prepared and their respective discussion.

More importantly, the report must provide a **reproducible** step-by-step guide on the following process:

-   data compilation, extraction and integration,
-   data cleaning, preparation and wrangling,
-   GIS analysis (including tabular and graphical analysis), and
-   GIS maps design.

> Note: **Reproducible** means that readers are able to perform the same analysis and obtain similar results by using the same data sets and by following the step-by-step guide.

The title of the report should be in the form of *SMT201_AY2022-23T1_Ex2*.

> Note: This is an individual exercise. You are required to work on the take home exercise and prepare submission individually.

## Grading

-   Quality of the GIS data model built (including metadata) (20 marks),
-   Appropriateness of the GIS methods used (20 marks),
-   Quality of GIS maps prepared (20 marks),
-   Reproducibility of the GIS processes (20 marks)
-   Ability to provide correct interpretation of the analysis results and to recommend appropriate alternatives (20 marks).

## Submission Date

The take-home exercise deliverable must be uploaded on eLearn by the submission deadline stated below.

Due Date: 16th October 2022, 11:59pm (midnight).
