---
title: "Lesson 11: Sharing Geographic Information on the Web: GeoWeb Mapping"
description: |
  In this lesson, you will learn the basic concepts of GeoWeb Mapping.  You will also gain hands-on experience on creating geoweb application using QGIS extension.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content

-   Motivation of GeoWeb Mapping
-   Getting to Know GeoWeb Mapping Technology
    -   GeoWeb mapping system architecture
    -   GeoWeb mapping protocol
    -   GeoWeb mapping systems
-   Evolution of GeoWeb Mapping
-   2nd Generation GeoWeb Mapping Technology
    -   OpenLayers
    -   Leaflet

## Lesson Slides and Hands-on Notes

-   Lesson slides in [html](../lesson/Lesson11/Lesson11.html) and [pdf](../lesson/Lesson11/Lesson11.pdf) formats.

-   Hands-on Exercise 11 in [html](../Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html) and [pdf](../Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.pdf) formats.

## References

### Concepts and Methods

-   [Web mapping](http://en.wikipedia.org/wiki/Web_mapping)
-   [7 great alternatives to the Google Maps API](http://www.creativebloq.com/inspiration/top-seven-alternatives-google-maps-api-7122779)
-   [Essential Resources: Mapping applications, frameworks and libraries](http://www.visualisingdata.com/index.php/2013/09/essential-resources-mapping-applications-frameworks-and-libraries/)
-   [Research Explores How to Keep Up With Changing Web Mapping Technology](http://www.directionsmag.com/articles/research-explores-how-to-keep-up-with-changing-web-mapping-technology/294410)

### Applications

### QGIS Methods

-   [qgis2web plugin](https://github.com/tomchadwin/qgis2web/wiki)
