---
title: "Lesson 9: Urban Network Analysis with GIS"
description: "In this lesson, you will learn the basic concepts of network data model and network analysis methods."
date: "`r Sys.Date()`"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content

-   Why analyse with network?
-   Network model
-   Real world network system
-   Complexity of urban road network
-   Shortest path analysis algorithm
-   Network analysis methods

## Lesson Slides and Hands-on Notes

-   Lesson slides in [html](../lesson/Lesson09/Lesson09.html) and [pdf](../lesson/Lesson09/Lesson09.pdf) formats.

-   Hands-on Exercise 9 in [html](https://gis4urbplan.netlify.app/hands-on_ex09) format.

## References

### Concepts and Methods

-   Manfred M. Fischer (2003) ["*GIS AND NETWORK ANALYSIS*"](https://www.researchgate.net/publication/23730944_GIS_and_network_analysis) in **Handbook 5 Transport Geography and Spatial Systems**. Hensher D., Button K., Haynes K. and Stopher P. (eds.); Pergamon

-   [5 Types of Network Analysis in GIS](https://gisgeography.com/network-analysis/)

-   Chun, Y, and Kim, H. (2018). [*Networks Defined*](https://gistbok.ucgis.org/bok-topics/2021-quarter-01/networks-defined). **The Geographic Information Science & Technology Body of Knowledge (4th Quarter 2018 Edition)**, John P. Wilson (Ed.).

### Applications

Lee, Jin ; Lubienski, Christopher (2017)
["The Impact of School Closures on Equity of Access in Chicago"](https://journals-sagepub-com.libproxy.smu.edu.sg/doi/full/10.1177/0013124516630601), *Education and Urban Society*, Vol.49 (1), p.53-80.

Jan Burdziej (2017) ["Using hexagonal grids and network analysis for spatial accessibility assessment in urban environments – a case study of public amenities in Toruń"](https://www.researchgate.net/publication/330850358_Using_hexagonal_grids_and_network_analysis_for_spatial_accessibility_assessment_in_urban_environments_-_A_case_study_of_public_amenities_in_Torun), *MISCELLANEA GEOGRAPHICA – REGIONAL STUDIES ON DEVELOPMENT*, Vol. 23, No. 2.

Rizwan Shahid, et al. (2009) ["Comparison of distance measures in spatial analytical modeling for health service planning"](https://bmchealthservres.biomedcentral.com/articles/10.1186/1472-6963-9-200), *BMC Health Services Research*, p1-14.  

### QGIS Methods

-   [QGIS Network Analysis Capabilities](https://www.giscourse.com/qgis-network-analysis-capabilities/)

-   [6.3. Lesson: Network Analysis](https://docs.qgis.org/3.22/en/docs/training_manual/vector_analysis/network_analysis.html) of QGIS Training Manual.

-   [About QNEAT3](https://root676.github.io/)
